/**
 * Flight Deck design reminder: the Scenario Lab turns a contemplated decision into a clear before-and-after cash outcome, then gives an actionable recommendation.
 */
import { useMemo, useState } from "react";
import { Sparkles } from "lucide-react";
import { toast } from "sonner";
import { ScenarioChart } from "@/components/finance-charts";
import { PageHeader, Panel, SectionLabel } from "@/components/finpilot-ui";
import { currency } from "@/data/mockData";

export default function ScenarioLab() {
  const [tab, setTab] = useState<"quick" | "ask">("quick"); const [revenue, setRevenue] = useState(10); const [expense, setExpense] = useState(5); const [monthly, setMonthly] = useState(50000); const [oneTime, setOneTime] = useState(100000); const [hires, setHires] = useState(2); const [salary, setSalary] = useState(40000); const [ran, setRan] = useState(false);
  const scenario = useMemo(() => Math.max(42000, 314000 + revenue * 2500 - expense * 1200 - monthly - oneTime - hires * salary - 11000), [revenue, expense, monthly, oneTime, hires, salary]);
  const impact = scenario - 314000; const health = Math.max(54, Math.min(87, Math.round(87 + impact / 15000)));
  const run = () => { setRan(true); toast("Scenario updated", { description: "FinPilot recalculated the 90-day cash position." }); };
  return <>
    <PageHeader eyebrow="Decision simulator" title="Test a decision before cash is committed" description="Model operating changes against your 90-day cash position and keep the reserve policy in view." />
    <section className="scenario-layout"><Panel className="scenario-control-panel"><SectionLabel>Build a scenario</SectionLabel><div className="scenario-tabs"><button className={tab === "quick" ? "active" : ""} onClick={() => setTab("quick")}>Quick simulator</button><button className={tab === "ask" ? "active" : ""} onClick={() => setTab("ask")}>Ask FinPilot</button></div>{tab === "quick" ? <><Range label="Revenue" value={revenue} display={`${revenue > 0 ? "+" : ""}${revenue}%`} min={-20} max={40} onChange={setRevenue} /><Range label="Expenses" value={expense} display={`${expense > 0 ? "+" : ""}${expense}%`} min={-20} max={30} onChange={setExpense} /><div className="field-pair"><Field label="New monthly expense" value={monthly} onChange={setMonthly} /><Field label="One-time expense" value={oneTime} onChange={setOneTime} /></div><div className="field-pair"><Field label="New hires" value={hires} onChange={setHires} plain /><Field label="Salary per hire" value={salary} onChange={setSalary} /></div></> : <div className="ask-scenario"><SectionLabel>What are you considering?</SectionLabel><textarea defaultValue="I want to hire 2 developers at ₹40K each starting next month." /><div className="drawer-detail"><span>Extracted monthly cost</span><strong>₹80,000</strong></div><div className="drawer-detail"><span>Forecast period</span><strong>90 days</strong></div></div>}<button className="button-primary" onClick={run}>{ran ? "Re-run simulation" : "Run simulation"}</button></Panel><Panel className="scenario-result-panel"><div className="scenario-result-head"><div><SectionLabel>90-day outcome</SectionLabel><h2>{ran ? "Your scenario forecast" : "Scenario preview"}</h2><p>Compare this decision with your current expected cash position.</p></div><div className="scenario-legend"><span><i />Current</span><span><i className="scenario-line" />Scenario</span></div></div><ScenarioChart scenario={scenario} /><div className="scenario-result-grid"><Result label="Current 90-day balance" value={currency(314000)} /><Result label="Scenario balance" value={currency(scenario)} /><Result label="Impact" value={`${impact < 0 ? "−" : "+"}${currency(Math.abs(impact))}`} negative={impact < 0} /><Result label="Health score" value={`87 → ${health}`} negative={health < 78} /></div><div className="recommendation-wide"><div className="spark"><Sparkles /></div><div><h3>FinPilot recommendation</h3><p>{scenario < 100000 ? "This scenario puts your business below the safety reserve. Hiring one employee instead of two would retain more cash flexibility." : "This scenario retains a usable cash buffer, but FinPilot recommends reviewing spend after the Sep 12 forecast trough."}</p></div></div></Panel></section>
  </>;
}
function Range({ label, value, display, min, max, onChange }: { label: string; value: number; display: string; min: number; max: number; onChange: (value: number) => void }) { return <div className="control-group"><label>{label}<strong>{display}</strong></label><input className="range-input" type="range" min={min} max={max} value={value} onChange={(event) => onChange(Number(event.target.value))} /></div>; }
function Field({ label, value, onChange, plain }: { label: string; value: number; onChange: (value: number) => void; plain?: boolean }) { return <div className="mini-field"><label>{label}</label><input value={value} onChange={(event) => onChange(Number(event.target.value.replace(/[^0-9]/g, "")))} inputMode="numeric" aria-label={label} /><small className="id-code">{plain ? "people" : "INR"}</small></div>; }
function Result({ label, value, negative }: { label: string; value: string; negative?: boolean }) { return <div className={`result-stat ${negative ? "negative" : ""}`}><span>{label}</span><strong>{value}</strong></div>; }
